AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Todo App API

Parameters:
  ClerkSecretArn:
    Type: String
    Description: ARN of the Clerk secret in AWS Secrets Manager
    Default: arn:aws:secretsmanager:us-west-2:894183034230:secret:todo-app/clerk-secret-key-8Y79tq

  DomainName:
    Type: String
    Description: Custom domain name (e.g., app.example.com). Leave empty to use CloudFront domain.
    Default: ""

  CertificateArn:
    Type: String
    Description: ACM certificate ARN (must be in us-east-1). Required if DomainName is set.
    Default: ""

Conditions:
  HasCustomDomain: !And
    - !Not [!Equals [!Ref DomainName, ""]]
    - !Not [!Equals [!Ref CertificateArn, ""]]

Globals:
  Function:
    Timeout: 10
    Runtime: nodejs22.x
    Environment:
      Variables:
        TABLE_NAME: !Ref TodoTable
        CLERK_SECRET_ARN: !Ref ClerkSecretArn

Resources:
  TodoTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: todo-app-todos
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: todoId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
        - AttributeName: todoId
          KeyType: RANGE
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true

  TodoApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: $default
      DefaultRouteSettings:
        ThrottlingBurstLimit: 20
        ThrottlingRateLimit: 10
      CorsConfiguration:
        AllowOrigins:
          - "https://app.cebarrett.me"
          - "http://localhost:5173"
          - "http://localhost:4173"
        AllowHeaders:
          - Content-Type
          - Authorization
        AllowMethods:
          - GET
          - POST
          - PUT
          - PATCH
          - DELETE
          - OPTIONS

  TodoFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: handler.handler
      MemorySize: 512
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TodoTable
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action: secretsmanager:GetSecretValue
              Resource: !Ref ClerkSecretArn
      Events:
        ListTodos:
          Type: HttpApi
          Properties:
            ApiId: !Ref TodoApi
            Path: /todos
            Method: GET
        CreateTodo:
          Type: HttpApi
          Properties:
            ApiId: !Ref TodoApi
            Path: /todos
            Method: POST
        UpdateTodo:
          Type: HttpApi
          Properties:
            ApiId: !Ref TodoApi
            Path: /todos/{todoId}
            Method: PUT
        DeleteTodo:
          Type: HttpApi
          Properties:
            ApiId: !Ref TodoApi
            Path: /todos/{todoId}
            Method: DELETE
        ReorderTodos:
          Type: HttpApi
          Properties:
            ApiId: !Ref TodoApi
            Path: /todos/reorder
            Method: PATCH
        Warmer:
          Type: Schedule
          Properties:
            Schedule: rate(5 minutes)
            Description: Keep Lambda warm to avoid cold starts

  # Frontend hosting resources
  FrontendBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "todo-app-frontend-${AWS::AccountId}"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  CloudFrontOAC:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: todo-app-oac
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  FrontendBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref FrontendBucket
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Action: s3:GetObject
            Resource: !Sub "${FrontendBucket.Arn}/*"
            Condition:
              StringEquals:
                AWS:SourceArn: !Sub "arn:aws:cloudfront::${AWS::AccountId}:distribution/${CloudFrontDistribution}"

  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        DefaultRootObject: index.html
        Aliases: !If
          - HasCustomDomain
          - - !Ref DomainName
          - !Ref AWS::NoValue
        Origins:
          - Id: S3Origin
            DomainName: !GetAtt FrontendBucket.RegionalDomainName
            OriginAccessControlId: !Ref CloudFrontOAC
            S3OriginConfig:
              OriginAccessIdentity: ""
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6
          ResponseHeadersPolicyId: 67f7725c-6f97-4210-82d7-5512b31e9d03  # SecurityHeadersPolicy
          Compress: true
        ViewerCertificate: !If
          - HasCustomDomain
          - AcmCertificateArn: !Ref CertificateArn
            SslSupportMethod: sni-only
            MinimumProtocolVersion: TLSv1.2_2021
          - CloudFrontDefaultCertificate: true
        CustomErrorResponses:
          - ErrorCode: 403
            ResponseCode: 200
            ResponsePagePath: /index.html
          - ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /index.html

  # ===========================================
  # AppSync GraphQL API (Phase 1 Migration)
  # ===========================================

  TodoGraphQLApi:
    Type: AWS::AppSync::GraphQLApi
    Properties:
      Name: todo-app-graphql
      AuthenticationType: AWS_LAMBDA
      LambdaAuthorizerConfig:
        AuthorizerUri: !GetAtt AuthFunction.Arn
        AuthorizerResultTtlInSeconds: 300
        IdentityValidationExpression: "^Bearer .+$"

  TodoGraphQLSchema:
    Type: AWS::AppSync::GraphQLSchema
    Properties:
      ApiId: !GetAtt TodoGraphQLApi.ApiId
      DefinitionS3Location: ./schema.graphql

  # Auth Lambda function for AppSync
  AuthFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: todo-app-auth
      CodeUri: ./
      Handler: auth.handler
      MemorySize: 256
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action: secretsmanager:GetSecretValue
              Resource: !Ref ClerkSecretArn

  # Permission for AppSync to invoke auth Lambda
  AuthFunctionAppSyncPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt AuthFunction.Arn
      Action: lambda:InvokeFunction
      Principal: appsync.amazonaws.com
      SourceArn: !GetAtt TodoGraphQLApi.Arn

  # Reorder Lambda function for AppSync
  ReorderFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: todo-app-reorder
      CodeUri: ./
      Handler: reorder.handler
      MemorySize: 256
      Environment:
        Variables:
          TABLE_NAME: !Ref TodoTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TodoTable

  # IAM Role for AppSync to access DynamoDB
  AppSyncDynamoDBRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: todo-app-appsync-dynamodb-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: appsync.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: DynamoDBAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                  - dynamodb:DeleteItem
                  - dynamodb:Query
                Resource: !GetAtt TodoTable.Arn

  # IAM Role for AppSync to invoke Lambda
  AppSyncLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: todo-app-appsync-lambda-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: appsync.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: LambdaInvoke
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: lambda:InvokeFunction
                Resource: !GetAtt ReorderFunction.Arn

  # DynamoDB Data Source
  TodosDataSource:
    Type: AWS::AppSync::DataSource
    Properties:
      ApiId: !GetAtt TodoGraphQLApi.ApiId
      Name: TodosTable
      Type: AMAZON_DYNAMODB
      DynamoDBConfig:
        AwsRegion: !Ref AWS::Region
        TableName: !Ref TodoTable
      ServiceRoleArn: !GetAtt AppSyncDynamoDBRole.Arn

  # Lambda Data Source for reorder operation
  ReorderLambdaDataSource:
    Type: AWS::AppSync::DataSource
    Properties:
      ApiId: !GetAtt TodoGraphQLApi.ApiId
      Name: ReorderLambda
      Type: AWS_LAMBDA
      LambdaConfig:
        LambdaFunctionArn: !GetAtt ReorderFunction.Arn
      ServiceRoleArn: !GetAtt AppSyncLambdaRole.Arn

  # ===========================================
  # AppSync Resolvers
  # ===========================================

  ListTodosResolver:
    Type: AWS::AppSync::Resolver
    DependsOn: TodoGraphQLSchema
    Properties:
      ApiId: !GetAtt TodoGraphQLApi.ApiId
      TypeName: Query
      FieldName: listTodos
      DataSourceName: !GetAtt TodosDataSource.Name
      RequestMappingTemplateS3Location: ./resolvers/listTodos.request.vtl
      ResponseMappingTemplateS3Location: ./resolvers/listTodos.response.vtl

  GetTodoResolver:
    Type: AWS::AppSync::Resolver
    DependsOn: TodoGraphQLSchema
    Properties:
      ApiId: !GetAtt TodoGraphQLApi.ApiId
      TypeName: Query
      FieldName: getTodo
      DataSourceName: !GetAtt TodosDataSource.Name
      RequestMappingTemplateS3Location: ./resolvers/getTodo.request.vtl
      ResponseMappingTemplateS3Location: ./resolvers/getTodo.response.vtl

  CreateTodoResolver:
    Type: AWS::AppSync::Resolver
    DependsOn: TodoGraphQLSchema
    Properties:
      ApiId: !GetAtt TodoGraphQLApi.ApiId
      TypeName: Mutation
      FieldName: createTodo
      DataSourceName: !GetAtt TodosDataSource.Name
      RequestMappingTemplateS3Location: ./resolvers/createTodo.request.vtl
      ResponseMappingTemplateS3Location: ./resolvers/createTodo.response.vtl

  UpdateTodoResolver:
    Type: AWS::AppSync::Resolver
    DependsOn: TodoGraphQLSchema
    Properties:
      ApiId: !GetAtt TodoGraphQLApi.ApiId
      TypeName: Mutation
      FieldName: updateTodo
      DataSourceName: !GetAtt TodosDataSource.Name
      RequestMappingTemplateS3Location: ./resolvers/updateTodo.request.vtl
      ResponseMappingTemplateS3Location: ./resolvers/updateTodo.response.vtl

  DeleteTodoResolver:
    Type: AWS::AppSync::Resolver
    DependsOn: TodoGraphQLSchema
    Properties:
      ApiId: !GetAtt TodoGraphQLApi.ApiId
      TypeName: Mutation
      FieldName: deleteTodo
      DataSourceName: !GetAtt TodosDataSource.Name
      RequestMappingTemplateS3Location: ./resolvers/deleteTodo.request.vtl
      ResponseMappingTemplateS3Location: ./resolvers/deleteTodo.response.vtl

  ReorderTodosResolver:
    Type: AWS::AppSync::Resolver
    DependsOn: TodoGraphQLSchema
    Properties:
      ApiId: !GetAtt TodoGraphQLApi.ApiId
      TypeName: Mutation
      FieldName: reorderTodos
      DataSourceName: !GetAtt ReorderLambdaDataSource.Name
      RequestMappingTemplateS3Location: ./resolvers/reorderTodos.request.vtl
      ResponseMappingTemplateS3Location: ./resolvers/reorderTodos.response.vtl

Outputs:
  ApiUrl:
    Description: API Gateway endpoint URL
    Value: !Sub "https://${TodoApi}.execute-api.${AWS::Region}.amazonaws.com"
  GraphQLApiEndpoint:
    Description: AppSync GraphQL endpoint URL
    Value: !GetAtt TodoGraphQLApi.GraphQLUrl
  GraphQLApiId:
    Description: AppSync GraphQL API ID
    Value: !GetAtt TodoGraphQLApi.ApiId
  FrontendUrl:
    Description: CloudFront distribution URL
    Value: !Sub "https://${CloudFrontDistribution.DomainName}"
  FrontendBucketName:
    Description: S3 bucket name for frontend deployment
    Value: !Ref FrontendBucket
  CloudFrontDistributionId:
    Description: CloudFront distribution ID (for cache invalidation)
    Value: !Ref CloudFrontDistribution
