AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Todo App API

Parameters:
  ClerkSecretArn:
    Type: String
    Description: ARN of the Clerk secret in AWS Secrets Manager
    Default: arn:aws:secretsmanager:us-west-2:894183034230:secret:todo-app/clerk-secret-key-8Y79tq

  DomainName:
    Type: String
    Description: Custom domain name (e.g., app.example.com). Leave empty to use CloudFront domain.
    Default: ""

  CertificateArn:
    Type: String
    Description: ACM certificate ARN (must be in us-east-1). Required if DomainName is set.
    Default: ""

Conditions:
  HasCustomDomain: !And
    - !Not [!Equals [!Ref DomainName, ""]]
    - !Not [!Equals [!Ref CertificateArn, ""]]

Globals:
  Function:
    Timeout: 10
    Runtime: nodejs22.x
    Environment:
      Variables:
        TABLE_NAME: !Ref TodoTable
        CLERK_SECRET_ARN: !Ref ClerkSecretArn

Resources:
  TodoTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: todo-app-todos
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: todoId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
        - AttributeName: todoId
          KeyType: RANGE

  TodoApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: $default
      DefaultRouteSettings:
        ThrottlingBurstLimit: 20
        ThrottlingRateLimit: 10
      CorsConfiguration:
        AllowOrigins:
          - "https://app.cebarrett.me"
          - "http://localhost:5173"
          - "http://localhost:4173"
        AllowHeaders:
          - Content-Type
          - Authorization
        AllowMethods:
          - GET
          - POST
          - PUT
          - PATCH
          - DELETE
          - OPTIONS

  TodoFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: handler.handler
      MemorySize: 512
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TodoTable
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action: secretsmanager:GetSecretValue
              Resource: !Ref ClerkSecretArn
      Events:
        ListTodos:
          Type: HttpApi
          Properties:
            ApiId: !Ref TodoApi
            Path: /todos
            Method: GET
        CreateTodo:
          Type: HttpApi
          Properties:
            ApiId: !Ref TodoApi
            Path: /todos
            Method: POST
        UpdateTodo:
          Type: HttpApi
          Properties:
            ApiId: !Ref TodoApi
            Path: /todos/{todoId}
            Method: PUT
        DeleteTodo:
          Type: HttpApi
          Properties:
            ApiId: !Ref TodoApi
            Path: /todos/{todoId}
            Method: DELETE
        ReorderTodos:
          Type: HttpApi
          Properties:
            ApiId: !Ref TodoApi
            Path: /todos/reorder
            Method: PATCH
        Warmer:
          Type: Schedule
          Properties:
            Schedule: rate(5 minutes)
            Description: Keep Lambda warm to avoid cold starts

  # Frontend hosting resources
  FrontendBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "todo-app-frontend-${AWS::AccountId}"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  CloudFrontOAC:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: todo-app-oac
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  FrontendBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref FrontendBucket
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Action: s3:GetObject
            Resource: !Sub "${FrontendBucket.Arn}/*"
            Condition:
              StringEquals:
                AWS:SourceArn: !Sub "arn:aws:cloudfront::${AWS::AccountId}:distribution/${CloudFrontDistribution}"

  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        DefaultRootObject: index.html
        Aliases: !If
          - HasCustomDomain
          - - !Ref DomainName
          - !Ref AWS::NoValue
        Origins:
          - Id: S3Origin
            DomainName: !GetAtt FrontendBucket.RegionalDomainName
            OriginAccessControlId: !Ref CloudFrontOAC
            S3OriginConfig:
              OriginAccessIdentity: ""
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6
          Compress: true
        ViewerCertificate: !If
          - HasCustomDomain
          - AcmCertificateArn: !Ref CertificateArn
            SslSupportMethod: sni-only
            MinimumProtocolVersion: TLSv1.2_2021
          - CloudFrontDefaultCertificate: true
        CustomErrorResponses:
          - ErrorCode: 403
            ResponseCode: 200
            ResponsePagePath: /index.html
          - ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /index.html

Outputs:
  ApiUrl:
    Description: API Gateway endpoint URL
    Value: !Sub "https://${TodoApi}.execute-api.${AWS::Region}.amazonaws.com"
  FrontendUrl:
    Description: CloudFront distribution URL
    Value: !Sub "https://${CloudFrontDistribution.DomainName}"
  FrontendBucketName:
    Description: S3 bucket name for frontend deployment
    Value: !Ref FrontendBucket
